version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/apps/api"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/apps/console-ui"
    schedule:
      interval: "weekly"

  - package-ecosystem: "nuget"
    directory: "/apps/maui/Capisoft.AI.TranscribeApp"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/infra/docker"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
